import { loadFlow, LoadedFlowExecuteFn } from '@flyde/runtime'
/*
    This file is generated by generated by @flyde/dev-server (probably via Flyde's VSCode extension)
    Manual changes might be lost - proceed with caution!
*/

declare module '@flyde/runtime' {

    // generated flow typings
    export function loadFlow(path: 'src/Main.flyde'): LoadedFlowExecuteFn<{}>;
}
