import { loadFlow, LoadedFlowExecuteFn } from '@flyde/runtime'
/*
    This file is generated by generated by @flyde/dev-server (probably via Flyde's VSCode extension)
    Manual changes might be lost - proceed with caution!
*/

declare module '@flyde/runtime' {

    // generated flow typings
    /**
    * @deprecated Path "node_modules/.bin/concurrently"" is corrupt. Please fix it.
    */
    export function loadFlow(path: 'node_modules/.bin/concurrently'): never;
    /**
    * @deprecated Path "node_modules/.bin/upgrade-blueprint-2.0.0-rename"" is corrupt. Please fix it.
    */
    export function loadFlow(path: 'node_modules/.bin/upgrade-blueprint-2.0.0-rename'): never;
    /**
    * @deprecated Path "node_modules/.bin/upgrade-blueprint-3.0.0-rename"" is corrupt. Please fix it.
    */
    export function loadFlow(path: 'node_modules/.bin/upgrade-blueprint-3.0.0-rename'): never;
}
