/// <reference path="@flyde/runtime/index.d.ts" />

/*
    This file is generated by flyde-cli. Please do not edit it.
*/

declare module '@flyde/runtime' {

    // generated flow typings
    export function executeFlow(path: 'debounce-throttle.flyde', args: {click: any}): Promise<any>;
    export function executeFlow(path: 'fibonacci.flyde', args: {n: any}): Promise<any>;
    export function executeFlow(path: 'hello-world.flyde', args: {}): Promise<any>;
    export function executeFlow(path: 'react-counter.flyde', args: {}): Promise<any>;

    // repeating static function typings.. TODO - find a way to avoid needing this
    export const expose: (func: Function, name: string, inputs?: string[]) => void;
}
