import { loadFlow, LoadedFlowExecuteFn } from '@flyde/runtime'
/*
    This file is generated by generated by @flyde/dev-server (probably via Flyde's VSCode extension)
    Manual changes might be lost - proceed with caution!
*/

declare module '@flyde/runtime' {

    // generated flow typings
    export function loadFlow(path: 'parts/Accumulate2.flyde'): LoadedFlowExecuteFn<{val: any}>;
    export function loadFlow(path: 'parts/AccumulateUntilTimeVis.flyde'): LoadedFlowExecuteFn<{item: any, time: any}>;
    export function loadFlow(path: 'parts/AssertProperties.flyde'): LoadedFlowExecuteFn<{object: any, properties: any}>;
    export function loadFlow(path: 'parts/Boolean Split.flyde'): LoadedFlowExecuteFn<{val: any}>;
    export function loadFlow(path: 'parts/HasProperty.flyde'): LoadedFlowExecuteFn<{obj: any, key: any}>;
    export function loadFlow(path: 'parts/HtmlBtn.flyde'): LoadedFlowExecuteFn<{children: any, className: any, style: any, extra: any, id: any}>;
    export function loadFlow(path: 'parts/HtmlDiv.flyde'): LoadedFlowExecuteFn<{children: any, className: any, style: any, extra: any, id: any}>;
    export function loadFlow(path: 'parts/HtmlH1.flyde'): LoadedFlowExecuteFn<{children: any, className: any, style: any, extra: any, id: any}>;
    export function loadFlow(path: 'parts/HtmlInput.flyde'): LoadedFlowExecuteFn<{children: any, className: any, style: any, extra: any, id: any, value: any, placeholder: any}>;
    export function loadFlow(path: 'parts/HtmlSpan.flyde'): LoadedFlowExecuteFn<{children: any, className: any, style: any, extra: any, id: any}>;
    export function loadFlow(path: 'parts/HtmlTextarea.flyde'): LoadedFlowExecuteFn<{children: any, className: any, style: any, extra: any, id: any, value: any, placeholder: any}>;
    export function loadFlow(path: 'parts/IncState.flyde'): LoadedFlowExecuteFn<{key: any, val: any}>;
    export function loadFlow(path: 'parts/Merge.flyde'): LoadedFlowExecuteFn<{a: any, b: any}>;
    export function loadFlow(path: 'parts/NewPart.flyde'): LoadedFlowExecuteFn<{f: any}>;
    export function loadFlow(path: 'parts/PropertyEquals.flyde'): LoadedFlowExecuteFn<{obj: any, key: any, compare: any}>;
    export function loadFlow(path: 'parts/SpreadList3.flyde'): LoadedFlowExecuteFn<{list: any}>;
    export function loadFlow(path: 'parts/http/HttpResponse.flyde'): LoadedFlowExecuteFn<{statusCode: any, body: any}>;
}
