/// <reference path="@flyde/runtime/index.d.ts" />

/*
    This file is generated by flyde-cli. Please do not edit it.
*/

declare module '@flyde/runtime' {

    // generated flow typings
    /**
    * @deprecated Path "parts/Accumulate.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Accumulate.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Accumulate2.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Accumulate2.flyde', args: never): never;
    /**
    * @deprecated Path "parts/AccumulateSome.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'AccumulateSome.flyde', args: never): never;
    /**
    * @deprecated Path "parts/AccumulateUntil.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'AccumulateUntil.flyde', args: never): never;
    /**
    * @deprecated Path "parts/AccumulateUntilTime.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'AccumulateUntilTime.flyde', args: never): never;
    /**
    * @deprecated Path "parts/AccumulateUntilTimeVis.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'AccumulateUntilTimeVis.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Add.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Add.flyde', args: never): never;
    /**
    * @deprecated Path "parts/AssertProperties.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'AssertProperties.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Boolean Split.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Boolean Split.flyde', args: never): never;
    /**
    * @deprecated Path "parts/CollectionCountDocuments.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'CollectionCountDocuments.flyde', args: never): never;
    /**
    * @deprecated Path "parts/CollectionDeleteOne.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'CollectionDeleteOne.flyde', args: never): never;
    /**
    * @deprecated Path "parts/CollectionFind.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'CollectionFind.flyde', args: never): never;
    /**
    * @deprecated Path "parts/CollectionFindOne.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'CollectionFindOne.flyde', args: never): never;
    /**
    * @deprecated Path "parts/CollectionFindOneAndUpdate.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'CollectionFindOneAndUpdate.flyde', args: never): never;
    /**
    * @deprecated Path "parts/CollectionInsertOne.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'CollectionInsertOne.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Cuid.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Cuid.flyde', args: never): never;
    /**
    * @deprecated Path "parts/DbCount.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'DbCount.flyde', args: never): never;
    /**
    * @deprecated Path "parts/DbFind.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'DbFind.flyde', args: never): never;
    /**
    * @deprecated Path "parts/DbFindOne.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'DbFindOne.flyde', args: never): never;
    /**
    * @deprecated Path "parts/DbInsert.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'DbInsert.flyde', args: never): never;
    /**
    * @deprecated Path "parts/DbRemove.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'DbRemove.flyde', args: never): never;
    /**
    * @deprecated Path "parts/DbUpdate.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'DbUpdate.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Debounce.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Debounce.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Delay.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Delay.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Delay2.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Delay2.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Divide.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Divide.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Dot.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Dot.flyde', args: never): never;
    /**
    * @deprecated Path "parts/EachMs.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'EachMs.flyde', args: never): never;
    /**
    * @deprecated Path "parts/EmptyList.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'EmptyList.flyde', args: never): never;
    /**
    * @deprecated Path "parts/EmptyObject.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'EmptyObject.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Equals.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Equals.flyde', args: never): never;
    /**
    * @deprecated Path "parts/FirstSecondOnlyRest.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'FirstSecondOnlyRest.flyde', args: never): never;
    /**
    * @deprecated Path "parts/FirstSecondRest.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'FirstSecondRest.flyde', args: never): never;
    /**
    * @deprecated Path "parts/FlattenArray.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'FlattenArray.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Floor.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Floor.flyde', args: never): never;
    /**
    * @deprecated Path "parts/FormatMessage.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'FormatMessage.flyde', args: never): never;
    /**
    * @deprecated Path "parts/FormatModel.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'FormatModel.flyde', args: never): never;
    /**
    * @deprecated Path "parts/GetItem.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'GetItem.flyde', args: never): never;
    /**
    * @deprecated Path "parts/GetListItem.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'GetListItem.flyde', args: never): never;
    /**
    * @deprecated Path "parts/GetState.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'GetState.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HOP_ListFilter-294_fn.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HOP_ListFilter-294_fn.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HOP_LlistMap-78_fn.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HOP_LlistMap-78_fn.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HOP_ScanValue-284_onValue.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HOP_ScanValue-284_onValue.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HOP_ScanValue-576_onValue.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HOP_ScanValue-576_onValue.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HOP_scan-588_onValue.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HOP_scan-588_onValue.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HasProperty.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HasProperty.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HeadCSS.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HeadCSS.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlBtn.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HtmlBtn.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlDiv.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HtmlDiv.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlH1.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HtmlH1.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlInput.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HtmlInput.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlSpan.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HtmlSpan.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlTag.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HtmlTag.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlTextarea.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HtmlTextarea.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlValueTag.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HtmlValueTag.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HttpGet.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HttpGet.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HttpPost.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HttpPost.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HttpRequest.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HttpRequest.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HttpResponse.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'HttpResponse.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Id.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Id.flyde', args: never): never;
    /**
    * @deprecated Path "parts/IncState.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'IncState.flyde', args: never): never;
    /**
    * @deprecated Path "parts/IndexOf.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'IndexOf.flyde', args: never): never;
    /**
    * @deprecated Path "parts/IsEmpty.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'IsEmpty.flyde', args: never): never;
    /**
    * @deprecated Path "parts/IsGreater bool .flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'IsGreater bool .flyde', args: never): never;
    /**
    * @deprecated Path "parts/IsGreater.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'IsGreater.flyde', args: never): never;
    /**
    * @deprecated Path "parts/LimitTimes.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'LimitTimes.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ListAppend.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ListAppend.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ListConcat2.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ListConcat2.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ListFilter.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ListFilter.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ListFrom2.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ListFrom2.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ListFrom3.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ListFrom3.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ListFromStr.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ListFromStr.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ListJoin.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ListJoin.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ListLength.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ListLength.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ListMap.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ListMap.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ListPrepend.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ListPrepend.flyde', args: never): never;
    /**
    * @deprecated Path "parts/MD5HashString.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'MD5HashString.flyde', args: never): never;
    /**
    * @deprecated Path "parts/MathMin.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'MathMin.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Merge.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Merge.flyde', args: never): never;
    /**
    * @deprecated Path "parts/MergeObjects.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'MergeObjects.flyde', args: never): never;
    /**
    * @deprecated Path "parts/MillisToDateString.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'MillisToDateString.flyde', args: never): never;
    /**
    * @deprecated Path "parts/MillisToString.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'MillisToString.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Modulo.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Modulo.flyde', args: never): never;
    /**
    * @deprecated Path "parts/MouseEvent.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'MouseEvent.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Multiply.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Multiply.flyde', args: never): never;
    /**
    * @deprecated Path "parts/NewPart.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'NewPart.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Now.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Now.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Object-builder-75360.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Object-builder-75360.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Parse.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Parse.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ParseInt.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ParseInt.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Pick.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Pick.flyde', args: never): never;
    /**
    * @deprecated Path "parts/PropertyEquals.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'PropertyEquals.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Publish.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Publish.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Random.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Random.flyde', args: never): never;
    /**
    * @deprecated Path "parts/RegexMatch.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'RegexMatch.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ReloadPage.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ReloadPage.flyde', args: never): never;
    /**
    * @deprecated Path "parts/RemoveAttr.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'RemoveAttr.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Repeat.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Repeat.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Replace.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Replace.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Round.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Round.flyde', args: never): never;
    /**
    * @deprecated Path "parts/RoundRobin3.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'RoundRobin3.flyde', args: never): never;
    /**
    * @deprecated Path "parts/ScanValue.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'ScanValue.flyde', args: never): never;
    /**
    * @deprecated Path "parts/SetAttr.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'SetAttr.flyde', args: never): never;
    /**
    * @deprecated Path "parts/SetItem.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'SetItem.flyde', args: never): never;
    /**
    * @deprecated Path "parts/SetState.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'SetState.flyde', args: never): never;
    /**
    * @deprecated Path "parts/SliceList.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'SliceList.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Split.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Split.flyde', args: never): never;
    /**
    * @deprecated Path "parts/SpreadList.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'SpreadList.flyde', args: never): never;
    /**
    * @deprecated Path "parts/SpreadList3.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'SpreadList3.flyde', args: never): never;
    /**
    * @deprecated Path "parts/SpreadList5.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'SpreadList5.flyde', args: never): never;
    /**
    * @deprecated Path "parts/SpreadListDelayed.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'SpreadListDelayed.flyde', args: never): never;
    /**
    * @deprecated Path "parts/StringAppend.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'StringAppend.flyde', args: never): never;
    /**
    * @deprecated Path "parts/StringIncludes.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'StringIncludes.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Stringify.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Stringify.flyde', args: never): never;
    /**
    * @deprecated Path "parts/SubStr.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'SubStr.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Subscribe.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Subscribe.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Subtract.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Subtract.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Switch.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Switch.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Test of debounce.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Test of debounce.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Test of subscribe.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Test of subscribe.flyde', args: never): never;
    /**
    * @deprecated Path "parts/TestOf3PinIssue.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'TestOf3PinIssue.flyde', args: never): never;
    /**
    * @deprecated Path "parts/TestOfAccSome.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'TestOfAccSome.flyde', args: never): never;
    /**
    * @deprecated Path "parts/TestOfIncState.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'TestOfIncState.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Tester of Merge.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Tester of Merge.flyde', args: never): never;
    /**
    * @deprecated Path "parts/TesterOfEmpty.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'TesterOfEmpty.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Throttle.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Throttle.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Transform.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Transform.flyde', args: never): never;
    /**
    * @deprecated Path "parts/UI tester.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'UI tester.flyde', args: never): never;
    /**
    * @deprecated Path "parts/WebScraper.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'WebScraper.flyde', args: never): never;
    /**
    * @deprecated Path "parts/concat.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'concat.flyde', args: never): never;
    /**
    * @deprecated Path "parts/epochToString.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'epochToString.flyde', args: never): never;
    /**
    * @deprecated Path "parts/isLess bool.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'isLess bool.flyde', args: never): never;
    /**
    * @deprecated Path "parts/isLess.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'isLess.flyde', args: never): never;
    /**
    * @deprecated Path "parts/isPropertyGreater.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'isPropertyGreater.flyde', args: never): never;
    /**
    * @deprecated Path "parts/testofpick.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'testofpick.flyde', args: never): never;

    // repeating static function typings.. TODO - find a way to avoid needing this
    export const expose: (func: Function, name: string, inputs?: string[]) => void;
}
