/// <reference path="@flyde/runtime/index.d.ts" />

/*
    This file is generated by flyde-cli. Please do not edit it.
*/

declare module '@flyde/runtime' {

    // generated flow typings
    /**
    * @deprecated Path "parts/Accumulate2.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'Accumulate2.flyde', args: never): never;
    /**
    * @deprecated Path "parts/AccumulateUntilTimeVis.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'AccumulateUntilTimeVis.flyde', args: never): never;
    /**
    * @deprecated Path "parts/AssertProperties.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'AssertProperties.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Boolean Split.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'Boolean Split.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HOP_ListFilter-294_fn.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HOP_ListFilter-294_fn.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HOP_LlistMap-78_fn.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HOP_LlistMap-78_fn.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HOP_ScanValue-284_onValue.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HOP_ScanValue-284_onValue.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HOP_ScanValue-576_onValue.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HOP_ScanValue-576_onValue.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HOP_scan-588_onValue.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HOP_scan-588_onValue.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HasProperty.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HasProperty.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlBtn.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HtmlBtn.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlDiv.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HtmlDiv.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlH1.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HtmlH1.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlInput.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HtmlInput.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlSpan.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HtmlSpan.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HtmlTextarea.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HtmlTextarea.flyde', args: never): never;
    /**
    * @deprecated Path "parts/HttpResponse.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'HttpResponse.flyde', args: never): never;
    /**
    * @deprecated Path "parts/IncState.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'IncState.flyde', args: never): never;
    /**
    * @deprecated Path "parts/Merge.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'Merge.flyde', args: never): never;
    /**
    * @deprecated Path "parts/NewPart.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'NewPart.flyde', args: never): never;
    /**
    * @deprecated Path "parts/PropertyEquals.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'PropertyEquals.flyde', args: never): never;
    /**
    * @deprecated Path "parts/SpreadList3.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'SpreadList3.flyde', args: never): never;
    /**
    * @deprecated Path "parts/UI tester.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'UI tester.flyde', args: never): never;

    // repeating static function typings.. TODO - find a way to avoid needing this
    export const expose: (func: Function, name: string, inputs?: string[]) => void;
}
