/// <reference path="@flyde/runtime/index.d.ts" />

/*
    This file is generated by flyde-cli. Please do not edit it.
*/

declare module '@flyde/runtime' {

    // generated flow typings
    /**
    * @deprecated Path "fixture/local-code-ref.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'local-code-ref.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/simple.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'simple.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/schema-validation/invalid/empty.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'empty.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/schema-validation/invalid/extraneous.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'extraneous.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/schema-validation/invalid/missing-must.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'missing-must.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/node_modules/@acme/multiply/src/multiply.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'multiply.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-non-exported-from-b/a.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'a.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-non-exported-from-b/b.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'b.flyde', args: never): never;
    export function executeFlow(path: 'a.flyde', args: {n: any}): Promise<any>;
    /**
    * @deprecated Path "fixture/a-imports-inline-fn-from-b/a.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'a.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-inline-fn-from-b/b.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'b.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-code-fn-from-package/a.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'a.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-code-fn-from-b/a.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'a.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-code-fn-from-b/b.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'b.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-b-with-internal-transitive-dep/a.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'a.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-b-with-internal-transitive-dep/b.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'b.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-b-with-2-level-internal-transitive-dep/a.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'a.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-b-with-2-level-internal-transitive-dep/b.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'b.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-aliased-part-from-b/a.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'a.flyde', args: never): never;
    /**
    * @deprecated Path "fixture/a-imports-aliased-part-from-b/b.flyde"" is corrupt. Please fix it."mainId" is missing.    */
    export function executeFlow(path: 'b.flyde', args: never): never;
    export function executeFlow(path: 'a.flyde', args: {n: any}): Promise<any>;

    // repeating static function typings.. TODO - find a way to avoid needing this
    export const expose: (func: Function, name: string, inputs?: string[]) => void;
}
