// /// <reference path="@flyde/runtime/index.d.ts" />

// /*
//     This file is generated by flyde-cli. Please do not edit it.
// */

// declare module '@flyde/runtime' {

//     // generated flow typings
//     /**
//     * @deprecated Path "src/flows/default-visual.flyde"" is corrupt. Please fix it.    */
//     export function executeFlow(path: 'default-visual.flyde', args: never): never;

//     // repeating static function typings.. TODO - find a way to avoid needing this
//     export const expose: (func: Function, name: string, inputs?: string[]) => void;
// }
