/// <reference path="@flyde/runtime/index.d.ts" />

/*
    This file is generated by flyde-cli. Please do not edit it.
*/

declare module '@flyde/runtime' {

    // generated flow typings
    /**
    * @deprecated Path "src/hello-world.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'hello-world.flyde', args: never): never;
    /**
    * @deprecated Path "src/loan-app.flyde"" is corrupt. Please fix it.    */
    export function executeFlow(path: 'loan-app.flyde', args: never): never;
    export function executeFlow(path: 'loan-app2.flyde', args: {a: any, b: any}): Promise<any>;
    export function executeFlow(path: 'new-flow.flyde', args: {formData: any}): Promise<any>;
    export function executeFlow(path: 'shared.flyde', args: {}): Promise<any>;
    export function executeFlow(path: 'my-flow.flyde', args: {}): Promise<any>;

    // repeating static function typings.. TODO - find a way to avoid needing this
    export const expose: (func: Function, name: string, inputs?: string[]) => void;
}
